[package]
name = "tablet_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
alsa = "0.9.1"
clap = { version = "4.5.16", features = ["derive"] }
byteorder = "1.5.0"
nix = {version="0.29.0", features=["user"]}
chrono = "0.4"
once_cell = "1.19.0"
